config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  # Defines the root path route ("/")
  root "contracts#index"

  get 'contracts/import', to: 'contracts#import', as: 'import_contracts'
  post 'contracts/process_csv', to: 'contracts#process_csv', as: 'process_csv'
  get '/contracts/supplier', to: 'contracts#supplier'

  resources :contracts do
    get :update_frame, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contract.rb
class Contract < ApplicationRecord
  acts_as_paranoid
  has_paper_trail

  # Validations
  validates :external_contract_id, presence: true, uniqueness: true
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true, comparison: { greater_than: :start_date }
  validates :value_cents, presence: true, numericality: { greater_than: 0 }

  # Associations
  belongs_to :contract_owner
  belongs_to :supplier, optional: false

  monetize :value_cents
end

app/models/contract_owner.rb
class ContractOwner < ApplicationRecord
  acts_as_paranoid
  has_paper_trail

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, email: { mode: :strict }

  # Associations
  has_many :contracts, dependent: :nullify
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  acts_as_paranoid
  has_paper_trail

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :identifier, presence: true, uniqueness: true

  # Associations
  has_many :contracts, dependent: :nullify

  before_validation :set_identifier

  def self.identifier_from_name(name)
    return if name.blank?

    name.downcase.gsub(/[[:space:]]/, '')
  end

  def average_contract_value
    sum = contracts.pluck(:value_cents).reduce(0, :+)
    average_value = sum / contracts.count

    Money.from_cents(average_value)
  end

  private

  def set_identifier
    self.identifier = Supplier.identifier_from_name(name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  def index
    @contracts = Contract
  end

  def supplier
    if params[:id].present?
      @supplier = Supplier.includes(contracts: :contract_owner).find_by(id: params[:id])

      redirect_to contracts_path, alert: "Supplier not found with id #{params[:id]}" if @supplier.nil?
    else
      redirect_to contracts_path, alert: 'Must have a valid Supplier'
    end
  end

  def import
    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def process_csv
    Turbo::StreamsChannel.broadcast_append_to(
      'notifications-content',
      action: :append,
      target: 'notifications-content',
      partial: 'contracts/notification',
      locals: { message: 'Your CSV upload is in progress', id: 'upload-started' }
    )

    csv_upload = params[:csv]

    blob = ActiveStorage::Blob.create_and_upload!(
      io: csv_upload.open,
      filename: csv_upload.original_filename,
      content_type: csv_upload.content_type
    )

    UploadContractsViaCsvJob.perform_async(blob.id)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contracts/_contract.html.erb
<div id=<%= "#{dom_id contract}" %> class="table-row text-gray-600 text-sm">
  <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= "#{contract.contract_owner.first_name} #{contract.contract_owner.last_name}" %></div>
  <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8">
    <%=
      button_tag "",
                 type: 'button',
                 class: "text-purple-600 hover:text-purple-800",
                 data: {
                   controller: "navigation",
                   action: "navigation#goTo",
                   path: "/contracts/supplier?id=#{contract.supplier.id}"
                 } do %>
      <%= contract.supplier.name %>
    <% end %>
  </div>
  <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= contract.name %></div>
  <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= contract.start_date %></div>
  <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= contract.end_date %></div>
  <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= contract.value.format %></div>
</div>

app/views/contracts/_notification.erb
<div id=<%= id %>>
  <div class="flex w-full flex-col items-center space-y-4 sm:items-end" id="notification-1">
    <div class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
      <div class="p-4">
        <div class="flex items-center">
          <div class="flex w-0 flex-1 justify-between">
            <p class="w-0 flex-1 text-sm font-medium text-gray-900"><%= message %></p>
          </div>
          <div class="ml-4 flex flex-shrink-0">
            <%=
              button_tag "",
                 type: 'button',
                 data: {
                   controller: "notifications",
                   action: "notifications#close",
                   notification_id: id
                 } do %>
              <span class="sr-only">Close</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
              </svg>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contracts/_upload_completion_notification.html.erb
<div id="upload-completion">
  <div class="flex w-full flex-col items-center space-y-4 sm:items-end" id="notification-1">
    <div class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
      <div class="p-4">
        <div class="flex items-start justify-between">
          <div class="flex flex-col gap-2">
            <p class="text-sm font-medium text-gray-900">Your contract import is completed!</p>
            <p class="text-sm text-gray-700">Contracts created: <%= contract_collection.valid_contracts.count %></p>
            <% if contract_collection.duplicate_contracts.count.positive? %>
              <p class="text-sm text-gray-700">Contracts updated: <%= contract_collection.duplicate_contracts.count %></p>
            <% end %>
            <% if contract_collection.invalid_contracts.count.positive? %>
              <p class="text-sm text-red-700">Invalid contracts: <%= contract_collection.invalid_contracts.count %></p>
              <div class="flex flex-col gap-2">
                <% contract_collection.invalid_contracts.each do |invalid_contract| %>
                  <div class="flex flex-col text-left">
                    <p class="text-xs text-gray-700">On row: <%= invalid_contract.row_number %></p>
                    <p class="text-xs text-gray-700"><%= invalid_contract.message %></p>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="ml-4 flex flex-shrink-0">
            <%=
              button_tag "",
                 type: 'button',
                 data: {
                   controller: "notifications",
                   action: "notifications#close",
                   notification_id: "upload-completion"
                 } do %>
              <span class="sr-only">Close</span>
              <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
              </svg>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contracts/import.html.erb
<turbo-frame id="import_frame">
  <div class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
      <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>
      <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
      <div class="inline-block align-bottom bg-white rounded-lg pt-5 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-xl sm:w-full">
        <form action="/contracts/process_csv" method="post" enctype="multipart/form-data" data-remote="true">
          <div class="pl-4 pb-4">
            <p class="text-left text-lg text-gray-600">Import Contracts</p>
          </div>
          <div class="border-t-2 border-b-2 border-gray-300">
            <div class="flex flex-col justify-center items-center text-center my-16 gap-2 mx-16">
              <svg width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M38 8L50 20H38V8ZM35 20C35 21.6875 36.3125 23 38 23H50V51.5C50 54.0312 47.9375 56 45.5 56H18.5C15.9688 56 14 54.0312 14 51.5V12.5C14 10.0625 15.9688 8 18.5 8H35V20ZM41 40.3438C41.9375 39.5 41.9375 38.0938 41 37.1562L33.5 29.6562C32.6562 28.8125 31.25 28.8125 30.4062 29.6562L22.9062 37.1562C21.9688 38.0938 21.9688 39.5 22.9062 40.3438C23.75 41.2812 25.1562 41.2812 26 40.3438L29.75 36.6875V46.25C29.75 47.5625 30.6875 48.5 32 48.5C33.2188 48.5 34.25 47.5625 34.25 46.25V36.6875L37.9062 40.3438C38.2812 40.8125 38.8438 41 39.5 41C40.0625 41 40.625 40.8125 41 40.3438Z" fill="#6A778A"/>
              </svg>
              <p class="text-gray-900">Upload a CSV here to Import Contracts</p>
              <label for="csv" class="text-purple-500 cursor-pointer hover:text-purple-700">Click here to select a file upload</label>
              <input type="file" id="csv" name="csv" accept=".csv" class="hidden" required>
            </div>
          </div>
          <div class="bg-gray-50">
          <div class="py-4 px-6 flex flex-row justify-between">
            <%= link_to "Cancel", "#",
              class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50",
              data: {
                controller: "modals",
                action: "modals#close"
              }
            %>
            <input type="submit" value="Import Contracts" class="inline-flex items-center gap-x-1.5 rounded-md bg-purple-500 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-purple-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-600">
          </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</turbo-frame>

app/views/contracts/index.html.erb
<div class="card-container mb-24">
  <div class="flex flex-row justify-between items-center px-8 py-4">
    <p class="text-lg">Contracts</p>
    <%=
      link_to import_contracts_path,
              class: 'inline-flex items-center gap-x-1.5 rounded-md bg-purple-500 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-purple-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-600',
              data: { turbo_frame: "import_frame" } do %>
      <svg width="12" height="16" viewBox="0 0 12 16" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M6.9375 11.5H5.0625C4.73438 11.5 4.5 11.2656 4.5 10.9375V7H2.4375C2.01562 7 1.80469 6.50781 2.10938 6.20312L5.67188 2.64062C5.83594 2.47656 6.14062 2.47656 6.30469 2.64062L9.86719 6.20312C10.1719 6.50781 9.96094 7 9.53906 7H7.5V10.9375C7.5 11.2656 7.24219 11.5 6.9375 11.5ZM12 11.3125V13.9375C12 14.2656 11.7422 14.5 11.4375 14.5H0.5625C0.234375 14.5 0 14.2656 0 13.9375V11.3125C0 11.0078 0.234375 10.75 0.5625 10.75H3.75V10.9375C3.75 11.6641 4.33594 12.25 5.0625 12.25H6.9375C7.64062 12.25 8.25 11.6641 8.25 10.9375V10.75H11.4375C11.7422 10.75 12 11.0078 12 11.3125ZM9.09375 13.375C9.09375 13.1172 8.88281 12.9062 8.625 12.9062C8.36719 12.9062 8.15625 13.1172 8.15625 13.375C8.15625 13.6328 8.36719 13.8438 8.625 13.8438C8.88281 13.8438 9.09375 13.6328 9.09375 13.375ZM10.5938 13.375C10.5938 13.1172 10.3828 12.9062 10.125 12.9062C9.86719 12.9062 9.65625 13.1172 9.65625 13.375C9.65625 13.6328 9.86719 13.8438 10.125 13.8438C10.3828 13.8438 10.5938 13.6328 10.5938 13.375Z" fill="white"/>
      </svg>
      Import Contracts
    <% end %>
  </div>
  <div class="flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="table table-auto w-full">
          <div class="table-header-group">
            <div class="table-row bg-gray-50 text-gray-800 text-sm">
              <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Owner</div>
              <div class="table-cell border-t border-gray-300 p-4 pl-8">Supplier</div>
              <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Name</div>
              <div class="table-cell border-t border-gray-300 p-4 pl-8">Start Date</div>
              <div class="table-cell border-t border-gray-300 p-4 pl-8">End Date</div>
              <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Value</div>
            </div>
          </div>
          <%= turbo_stream_from "contracts" %>
          <turbo-frame class="table-row-group" id="contracts">
            <%= render @contracts.includes(:supplier, :contract_owner) %>
          </turbo-frame>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contracts/process_csv.turbo_stream.erb
<turbo-stream action="remove" target="import_frame"></turbo-stream>

app/views/contracts/supplier.html.erb
<div>
  <%=
    button_tag "",
               type: 'button',
               class: "text-purple-600 hover:text-purple-800",
               data: {
                 controller: "navigation",
                 action: "navigation#goTo",
                 path: "/contracts"
               } do %>
    <div class="flex flex-row items-center gap-1 mb-3">
      <svg width="11" height="10" viewBox="0 0 11 10" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M10.7266 5.5C10.7266 5.92188 10.3984 6.25 10 6.25H2.80469L5.26562 8.73438C5.57031 9.01562 5.57031 9.50781 5.26562 9.78906C5.125 9.92969 4.9375 10 4.75 10C4.53906 10 4.35156 9.92969 4.21094 9.78906L0.460938 6.03906C0.15625 5.75781 0.15625 5.26562 0.460938 4.98438L4.21094 1.23438C4.49219 0.929688 4.98438 0.929688 5.26562 1.23438C5.57031 1.51562 5.57031 2.00781 5.26562 2.28906L2.80469 4.75H10C10.3984 4.75 10.7266 5.10156 10.7266 5.5Z" fill="#6B63E8"/>
      </svg>
      All Contracts
    </div>
  <% end %>
  <div class="card-container mb-24">
    <div class="flex flex-row justify-between items-center px-8 py-4">
      <p class="text-lg"><%= @supplier.name %> Contracts</p>
      <div class="flex flex-col text-right">
        <p class="text-md text-black">AVERAGE CONTRACT VALUE</p>
        <p class="text-lg text-black font-semibold"><%= @supplier.average_contract_value.format %></p>
      </div>
    </div>
    <div class="flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <div class="table table-auto w-full">
            <div class="table-header-group">
              <div class="table-row bg-gray-50 text-gray-800 text-sm">
                <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Owner</div>
                <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Name</div>
                <div class="table-cell border-t border-gray-300 p-4 pl-8">Start Date</div>
                <div class="table-cell border-t border-gray-300 p-4 pl-8">End Date</div>
                <div class="table-cell border-t border-gray-300 p-4 pl-8">Contract Value</div>
              </div>
            </div>
            <div class="table-row-group">
              <% @supplier.contracts.each do |contract| %>
                <div id=<%= "#{contract.id}" %> class="table-row text-gray-600 text-sm">
                <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= "#{contract.contract_owner.first_name} #{contract.contract_owner.last_name}" %></div>
                <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= contract.name %></div>
                <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= contract.start_date %></div>
                <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= contract.end_date %></div>
                <div class="table-cell whitespace-nowrap border-t border-gray-300 p-4 pl-8"><%= contract.value.format %></div>
                </div>
              <% end %>
              </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="bg-white border-gray-200 bg-white border-b border-gray-300 fixed w-full top-0">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <span class="self-center text-2xl font-semibold whitespace-nowrap">Tropic</span>
    <div class="block w-auto" id="navbar-default">
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<div aria-live="assertive" class="pointer-events-none inset-0 fixed z-10 px-4 py-2 sm:items-start sm:p-2">
  <%= turbo_stream_from "notifications-content" %>
  <turbo-frame class="flex flex-col gap-2" id="notifications-content" ></turbo-frame>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TropicTakeHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-purple-50 h-full w-full">
    <%= render partial: "layouts/notifications" %>

    <%= render partial: "layouts/nav" %>

    <main class="container mx-auto mt-28 px-5">
      <%= render partial: "shared/flash_messages" %>

      <%= yield %>
    </main>

    <%= turbo_frame_tag "import_frame" %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>